SELECT MIN(START_DATE), MAX(END_DATE) 
FROM (SELECT START_DATE, END_DATE, (
      START_DATE - ROW_NUMBER() OVER (
      ORDER BY START_DATE
      )
      ) PP FROM Projects
      ) PP1 
GROUP BY PP 
ORDER BY MIN(START_DATE)- MAX(END_DATE) DESC;